[project]
name = "nanotherm"
version = "0.0.1.dev0"
description = "A project on Radiofrequency Ablation (RFA) by Metala Nanofluidos"
authors = [
    {name = "VCOliver",email = "victorcruz.01@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = [
    "numpy (>=2.3.0,<3.0.0)",
    "scipy (>=1.15.3,<2.0.0)",
    "matplotlib (>=3.10.3,<4.0.0)",
    "toml (>=0.10.2,<0.11.0)"
]

[tool.poetry]
packages = [{include = "nanotherm", from = "src"}]


[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"
pandas = "^2.3.0"
pre-commit = "^4.2.0"


[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.1"
mkdocs-material = "^9.6.14"
mkdocstrings = {extras = ["python"], version = "^0.29.1"}
pymdown-extensions = "^10.15"
python-markdown-math = "^0.9"
mkdocs-autolinks-plugin = "^0.7.1"
mike = "^2.1.3"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
nanotherm = "nanotherm.__main__:main"
