[logging]
level = "DEBUG"
format = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
date_format = "%d-%m-%Y %H:%M:%S"

[pid]
kp = 1.0
ki = 0.2
kd = 0.05

# This should be deleted later
setpoint = 1.0
